run:
  timeout: 3m
  tests: true

linters:
  enable:
    - govet
    - gofmt
    - staticcheck
    - gosimple
    - errcheck
    - ineffassign
    - unused
    - gocyclo
    - typecheck

linters-settings:
  gocyclo:
    min-complexity: 18

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
